#!/usr/bin/env python

Import("env")

import main_builders

env.main_sources = []

env_main = env.Clone()

env_main.add_source_files(env.main_sources, "*.cpp")

if env["tests"]:
    env_main.Append(CPPDEFINES=["TESTS_ENABLED"])

env_main.Depends("#main/splash.gen.h", "#main/splash.png")
env_main.Depends("#main/splash_editor.gen.h", "#main/splash_editor.png")
env_main.Depends("#main/app_icon.gen.h", "#main/app_icon.png")

lib = env_main.add_library("main", env.main_sources)
env.Prepend(LIBS=[lib])
