#!/usr/bin/env python

Import("env")

env = env.Clone()

# Thirdparty source files
# Not unbundled for now as they are not commonly available as shared library
thirdparty_dir = "#thirdparty/jpeg-compressor/"

env.Prepend(CPPPATH=[thirdparty_dir])
env.Library(target="jpg_thirdparty", source=[thirdparty_dir + "jpgd.cpp"])

env.Library(target="jpg", source=Glob("*.cpp"), libdeps=["jpg_thirdparty"])
