#!/usr/bin/env python

Import("env")
Import("env_modules")

env_fbx_importer = env_modules.Clone()

# Godot's own source files
env_fbx_importer.add_source_files(env.modules_sources, "tools/**.cpp")
env_fbx_importer.add_source_files(env.modules_sources, "data/**.cpp")
env_fbx_importer.add_source_files(env.modules_sources, "data/FBX/**.cpp")
env_fbx_importer.add_source_files(env.modules_sources, "**.cpp")
