#!/usr/bin/env python

Import("env")

env.platform_sources = []

# Register platform-exclusive APIs
for platform in env.platform_apis:
    platform_dir = env.Dir(platform)
    env.add_source_files(env.platform_sources, platform + "/api/api.cpp")


env.add_source_files(env.platform_sources, "register_platform_apis.gen.cpp")

lib = env.add_library("platform", env.platform_sources)
env.Prepend(LIBS=[lib])
