name: Godot CI

on:
    pull_request:
    push:
      branches: [ master, 3.2, 3.1, 3.0 ]
jobs:
  windows-editor:
    runs-on: windows-latest
    name: Windows Editor
    env:
      SCONS_CACHE: ~/.scons_cache/
      SCONS_CACHE_LIMIT: 2048  
    steps:
    - uses: actions/checkout@v2
    - name: configure .scons_cache and download cache
      id: scons-cache
      uses: actions/cache@v2
      with:
        path: ~/.scons_cache/**
        key: ${{ runner.os }}-release_debug
        restore-keys: ${{ runner.os }}-release_debug
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64' 
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Installation scons
      run: |
        python -m pip install scons pywin32
    - name: Check versioning
      run: |
        python --version
        scons --version
    - name: Compilation
      run: |
        scons -j2 warnings=all werror=yes platform=windows target=release_debug
    - name: publishing godot windows-editor
      uses: actions/upload-artifact@v1
      with:
        name: windows-editor
        path: bin/godot.windows.opt.tools.64.exe
  windows-release:
    runs-on: windows-latest
    name: Windows Release
    env:
     SCONS_CACHE: ~/.scons_cache/ 
     SCONS_CACHE_LIMIT: 2048
    steps:
    - uses: actions/checkout@v2
    - name: configure .scons_cache and download cache
      id: scons-cache
      uses: actions/cache@v2
      with:
        path: ~/.scons_cache/**
        key: ${{ runner.os }}-release_debug
        restore-keys: ${{ runner.os }}-release_debug
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64' 
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Installation scons
      run: |
        python -m pip install scons pywin32
    - name: Check versioning
      run: |
        python --version
        scons --version
    - name: Compilation
      run: |
        scons -j2 platform=windows tools=no warnings=all werror=yes target=release
    - name: publishing godot windows-player
      uses: actions/upload-artifact@v1
      with:
        name: windows-player
        path: bin/godot.windows.opt.64.exe 
